services:
  vite-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-certs:/etc/letsencrypt
    environment:
      - NODE_ENV=production
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-certs:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 360h; done;'"
    command: >
      certbot certonly --webroot --webroot-path=/usr/share/nginx/html
      --email seuemail@exemplo.com --agree-tos --no-eff-email
      --force-renewal -d seusite.com -d www.seusite.com
    depends_on:
      - vite-prod
    environment:
      - TZ=America/Sao_Paulo

volumes:
  certbot-certs:
  